version: '3.1'

services:
  drupal:
    image: drupal
    volumes:
      - /var/www/html/modules
      - /var/www/html/profiles
      - /var/www/html/themes
      - /var/www/html/sites
    ports:
      - 8080:80
    restart: always

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    restart: always
  