version: '3.1'

services:
  drupal:
    image: drupal
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    ports:
      - 8080:80
    restart: always

  postgres:
    image: postgres
    volumes:
      - drupal-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: example
    restart: always

volumes:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites:
  drupal-data: