# create your drupal and postgres config here, based off the last assignment

version: '3.1'

services:
  custom-drupal:
    build: . 
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    ports:
      - 8080:80
    restart: always

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - drupal-data:/var/lib/postgresql/data
    restart: always
volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-themes:
  drupal-sites: